version: '3'

services:
  app:
    image: seerbitmiddleware.azurecr.io/image-workflow-1686784333642
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=production
