apiVersion: v1
kind: Service
metadata:
  name: ingress-service
spec:
  selector:
    app: seerbit-middleware-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
