name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          docker-compose build
          docker-compose push

      - name: Log in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: your-container-registry
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for Application to Start
        run: sleep 30s

      - name: Run Integration Tests
        run: |
          # Replace with your integration test command

      - name: Tear Down Deployment
        run: |
          docker-compose down
